<?php

return [
    "Afghanistan" => ["shipping" => 25.00, "code" => "AF"],
    "Albania" => ["shipping" => 15.00, "code" => "AL"],
    "Algeria" => ["shipping" => 20.00, "code" => "DZ"],
    "Andorra" => ["shipping" => 18.00, "code" => "AD"],
    "Angola" => ["shipping" => 30.00, "code" => "AO"],
    "Antigua and Barbuda" => ["shipping" => 28.00, "code" => "AG"],
    "Argentina" => ["shipping" => 22.00, "code" => "AR"],
    "Armenia" => ["shipping" => 12.00, "code" => "AM"],
    "Australia" => ["shipping" => 15.00, "code" => "AU"],
    "Austria" => ["shipping" => 10.00, "code" => "AT"],
    "Azerbaijan" => ["shipping" => 14.00, "code" => "AZ"],
    "Bahamas" => ["shipping" => 35.00, "code" => "BS"],
    "Bahrain" => ["shipping" => 17.00, "code" => "BH"],
    "Bangladesh" => ["shipping" => 25.00, "code" => "BD"],
    "Barbados" => ["shipping" => 33.00, "code" => "BB"],
    "Belarus" => ["shipping" => 16.00, "code" => "BY"],
    "Belgium" => ["shipping" => 12.00, "code" => "BE"],
    "Belize" => ["shipping" => 23.00, "code" => "BZ"],
    "Benin" => ["shipping" => 27.00, "code" => "BJ"],
    "Bhutan" => ["shipping" => 32.00, "code" => "BT"],
    "Bolivia" => ["shipping" => 24.00, "code" => "BO"],
    "Bosnia and Herzegovina" => ["shipping" => 13.00, "code" => "BA"],
    "Botswana" => ["shipping" => 28.00, "code" => "BW"],
    "Brazil" => ["shipping" => 18.00, "code" => "BR"],
    "Brunei" => ["shipping" => 20.00, "code" => "BN"],
    "Bulgaria" => ["shipping" => 14.00, "code" => "BG"],
    "Burkina Faso" => ["shipping" => 29.00, "code" => "BF"],
    "Burundi" => ["shipping" => 34.00, "code" => "BI"],
    "Cabo Verde" => ["shipping" => 26.00, "code" => "CV"],
    "Cambodia" => ["shipping" => 19.00, "code" => "KH"],
    "Cameroon" => ["shipping" => 31.00, "code" => "CM"],
    "Canada" => ["shipping" => 12.00, "code" => "CA"],
    "Central African Republic" => ["shipping" => 36.00, "code" => "CF"],
    "Chad" => ["shipping" => 30.00, "code" => "TD"],
    "Chile" => ["shipping" => 22.00, "code" => "CL"],
    "China" => ["shipping" => 15.00, "code" => "CN"],
    "Colombia" => ["shipping" => 20.00, "code" => "CO"],
    "Comoros" => ["shipping" => 35.00, "code" => "KM"],
    "Congo (Congo-Brazzaville)" => ["shipping" => 28.00, "code" => "CG"],
    "Costa Rica" => ["shipping" => 24.00, "code" => "CR"],
    "Croatia" => ["shipping" => 16.00, "code" => "HR"],
    "Cuba" => ["shipping" => 33.00, "code" => "CU"],
    "Cyprus" => ["shipping" => 14.00, "code" => "CY"],
    "Czechia (Czech Republic)" => ["shipping" => 13.00, "code" => "CZ"],
    "Denmark" => ["shipping" => 11.00, "code" => "DK"],
    "Djibouti" => ["shipping" => 27.00, "code" => "DJ"],
    "Dominica" => ["shipping" => 32.00, "code" => "DM"],
    "Dominican Republic" => ["shipping" => 21.00, "code" => "DO"],
    "Ecuador" => ["shipping" => 18.00, "code" => "EC"],
    "Egypt" => ["shipping" => 15.00, "code" => "EG"],
    "El Salvador" => ["shipping" => 23.00, "code" => "SV"],
    "Equatorial Guinea" => ["shipping" => 30.00, "code" => "GQ"],
    "Eritrea" => ["shipping" => 34.00, "code" => "ER"],
    "Estonia" => ["shipping" => 10.00, "code" => "EE"],
    "Eswatini (fmr. Swaziland)" => ["shipping" => 28.00, "code" => "SZ"],
    "Ethiopia" => ["shipping" => 26.00, "code" => "ET"],
    "Fiji" => ["shipping" => 35.00, "code" => "FJ"],
    "Finland" => ["shipping" => 12.00, "code" => "FI"],
    "France" => ["shipping" => 10.00, "code" => "FR"],
    "Gabon" => ["shipping" => 29.00, "code" => "GA"],
    "Gambia" => ["shipping" => 33.00, "code" => "GM"],
    "Georgia" => ["shipping" => 15.00, "code" => "GE"],
    "Germany" => ["shipping" => 12.00, "code" => "DE"],
    "Ghana" => ["shipping" => 31.00, "code" => "GH"],
    "Greece" => ["shipping" => 13.00, "code" => "GR"],
    "Grenada" => ["shipping" => 32.00, "code" => "GD"],
    "Guatemala" => ["shipping" => 23.00, "code" => "GT"],
    "Guinea" => ["shipping" => 30.00, "code" => "GN"],
    "Guinea-Bissau" => ["shipping" => 34.00, "code" => "GW"],
    "Guyana" => ["shipping" => 25.00, "code" => "GY"],
    "Haiti" => ["shipping" => 28.00, "code" => "HT"],
    "Honduras" => ["shipping" => 22.00, "code" => "HN"],
    "Hungary" => ["shipping" => 11.00, "code" => "HU"],
    "Iceland" => ["shipping" => 15.00, "code" => "IS"],
    "India" => ["shipping" => 14.00, "code" => "IN"],
    "Indonesia" => ["shipping" => 18.00, "code" => "ID"],
    "Iran" => ["shipping" => 20.00, "code" => "IR"],
    "Iraq" => ["shipping" => 27.00, "code" => "IQ"],
    "Ireland" => ["shipping" => 10.00, "code" => "IE"],
    "Israel" => ["shipping" => 17.00, "code" => "IL"],
    "Italy" => ["shipping" => 12.00, "code" => "IT"],
    "Jamaica" => ["shipping" => 22.00, "code" => "JM"],
    "Japan" => ["shipping" => 13.00, "code" => "JP"],
    "Jordan" => ["shipping" => 25.00, "code" => "JO"],
    "Kazakhstan" => ["shipping" => 20.00, "code" => "KZ"],
    "Kenya" => ["shipping" => 30.00, "code" => "KE"],
    "Kiribati" => ["shipping" => 32.00, "code" => "KI"],
    "Korea (North)" => ["shipping" => 35.00, "code" => "KP"],
    "Korea (South)" => ["shipping" => 15.00, "code" => "KR"],
    "Kuwait" => ["shipping" => 20.00, "code" => "KW"],
    "Kyrgyzstan" => ["shipping" => 18.00, "code" => "KG"],
    "Laos" => ["shipping" => 23.00, "code" => "LA"],
    "Latvia" => ["shipping" => 12.00, "code" => "LV"],
    "Lebanon" => ["shipping" => 17.00, "code" => "LB"],
    "Lesotho" => ["shipping" => 27.00, "code" => "LS"],
    "Liberia" => ["shipping" => 29.00, "code" => "LR"],
    "Libya" => ["shipping" => 24.00, "code" => "LY"],
    "Liechtenstein" => ["shipping" => 14.00, "code" => "LI"],
    "Lithuania" => ["shipping" => 13.00, "code" => "LT"],
    "Luxembourg" => ["shipping" => 10.00, "code" => "LU"],
    "Madagascar" => ["shipping" => 31.00, "code" => "MG"],
    "Malawi" => ["shipping" => 26.00, "code" => "MW"],
    "Malaysia" => ["shipping" => 15.00, "code" => "MY"],
    "Maldives" => ["shipping" => 28.00, "code" => "MV"],
    "Mali" => ["shipping" => 33.00, "code" => "ML"],
    "Malta" => ["shipping" => 11.00, "code" => "MT"],
    "Marshall Islands" => ["shipping" => 30.00, "code" => "MH"],
    "Mauritania" => ["shipping" => 32.00, "code" => "MR"],
    "Mauritius" => ["shipping" => 22.00, "code" => "MU"],
    "Mexico" => ["shipping" => 18.00, "code" => "MX"],
    "Micronesia" => ["shipping" => 34.00, "code" => "FM"],
    "Moldova" => ["shipping" => 16.00, "code" => "MD"],
    "Monaco" => ["shipping" => 12.00, "code" => "MC"],
    "Mongolia" => ["shipping" => 21.00, "code" => "MN"],
    "Montenegro" => ["shipping" => 14.00, "code" => "ME"],
    "Morocco" => ["shipping" => 19.00, "code" => "MA"],
    "Mozambique" => ["shipping" => 29.00, "code" => "MZ"],
    "Myanmar" => ["shipping" => 20.00, "code" => "MM"],
    "Namibia" => ["shipping" => 26.00, "code" => "NA"],
    "Nauru" => ["shipping" => 35.00, "code" => "NR"],
    "Nepal" => ["shipping" => 25.00, "code" => "NP"],
    "Netherlands" => ["shipping" => 10.00, "code" => "NL"],
    "New Zealand" => ["shipping" => 18.00, "code" => "NZ"],
    "Nicaragua" => ["shipping" => 24.00, "code" => "NI"],
    "Niger" => ["shipping" => 32.00, "code" => "NE"],
    "Nigeria" => ["shipping" => 30.00, "code" => "NG"],
    "North Macedonia" => ["shipping" => 15.00, "code" => "MK"],
    "Norway" => ["shipping" => 12.00, "code" => "NO"],
    "Oman" => ["shipping" => 17.00, "code" => "OM"],
    "Pakistan" => ["shipping" => 19.00, "code" => "PK"],
    "Palau" => ["shipping" => 28.00, "code" => "PW"],
    "Panama" => ["shipping" => 23.00, "code" => "PA"],
    "Papua New Guinea" => ["shipping" => 35.00, "code" => "PG"],
    "Paraguay" => ["shipping" => 22.00, "code" => "PY"],
    "Peru" => ["shipping" => 21.00, "code" => "PE"],
    "Philippines" => ["shipping" => 16.00, "code" => "PH"],
    "Poland" => ["shipping" => 11.00, "code" => "PL"],
    "Portugal" => ["shipping" => 13.00, "code" => "PT"],
    "Qatar" => ["shipping" => 20.00, "code" => "QA"],
    "Romania" => ["shipping" => 15.00, "code" => "RO"],
    "Russia" => ["shipping" => 25.00, "code" => "RU"],
    "Rwanda" => ["shipping" => 28.00, "code" => "RW"],
    "Saint Kitts and Nevis" => ["shipping" => 30.00, "code" => "KN"],
    "Saint Lucia" => ["shipping" => 29.00, "code" => "LC"],
    "Saint Vincent and the Grenadines" => ["shipping" => 27.00, "code" => "VC"],
    "Samoa" => ["shipping" => 35.00, "code" => "WS"],
    "San Marino" => ["shipping" => 10.00, "code" => "SM"],
    "Sao Tome and Principe" => ["shipping" => 32.00, "code" => "ST"],
    "Saudi Arabia" => ["shipping" => 20.00, "code" => "SA"],
    "Senegal" => ["shipping" => 26.00, "code" => "SN"],
    "Serbia" => ["shipping" => 14.00, "code" => "RS"],
    "Seychelles" => ["shipping" => 28.00, "code" => "SC"],
    "Sierra Leone" => ["shipping" => 31.00, "code" => "SL"],
    "Singapore" => ["shipping" => 12.00, "code" => "SG"],
    "Slovakia" => ["shipping" => 15.00, "code" => "SK"],
    "Slovenia" => ["shipping" => 13.00, "code" => "SI"],
    "Solomon Islands" => ["shipping" => 34.00, "code" => "SB"],
    "Somalia" => ["shipping" => 33.00, "code" => "SO"],
    "South Africa" => ["shipping" => 18.00, "code" => "ZA"],
    "South Sudan" => ["shipping" => 29.00, "code" => "SS"],
    "Spain" => ["shipping" => 12.00, "code" => "ES"],
    "Sri Lanka" => ["shipping" => 20.00, "code" => "LK"],
    "Sudan" => ["shipping" => 27.00, "code" => "SD"],
    "Suriname" => ["shipping" => 23.00, "code" => "SR"],
    "Sweden" => ["shipping" => 11.00, "code" => "SE"],
    "Switzerland" => ["shipping" => 10.00, "code" => "CH"],
    "Syria" => ["shipping" => 22.00, "code" => "SY"],
    "Taiwan" => ["shipping" => 15.00, "code" => "TW"],
    "Tajikistan" => ["shipping" => 19.00, "code" => "TJ"],
    "Tanzania" => ["shipping" => 28.00, "code" => "TZ"],
    "Thailand" => ["shipping" => 16.00, "code" => "TH"],
    "Timor-Leste" => ["shipping" => 30.00, "code" => "TL"],
    "Togo" => ["shipping" => 32.00, "code" => "TG"],
    "Tonga" => ["shipping" => 35.00, "code" => "TO"],
    "Trinidad and Tobago" => ["shipping" => 24.00, "code" => "TT"],
    "Tunisia" => ["shipping" => 21.00, "code" => "TN"],
    "Turkey" => ["shipping" => 14.00, "code" => "TR"],
    "Turkmenistan" => ["shipping" => 25.00, "code" => "TM"],
    "Tuvalu" => ["shipping" => 35.00, "code" => "TV"],
];
